language: python

python:
  - 2.7

install:
    - pip install --use-mirrors -r requirements/local.txt
    - pip install coverage coveralls
    - pip install dj-static==0.0.5

before_script:
  - ./lint.sh
  
notifications:
  slack: agiliq:4rM97fcM3RrHNA3EssNXYG3V  

script:  coverage run manage.py test

after_success: coveralls
