language: python

python:
  - 2.7

install:
    - pip install -r requirements.txt
    - pip install coverage coveralls

before_script:
  - ./lint.sh

script:  coverage run manage.py test

after_success: coveralls