language: python

python:
  - 2.7

install:
    - pip install -r --use-mirrors requirements/dev.txt
    - pip install -r --use-mirrors requirements/project.txt
    - pip install coverage coveralls

before_script:
  - ./lint.sh

script:  coverage run manage.py test

after_success: coveralls