from django.conf.urls import patterns, url

from tavern import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^groups/(?P<slug>[\w-]+)/$',
                           views.group_details, name='tavern_group_details'),
                       url(r'^create_group/',
                           views.create_group, name='tavern_create_group'),
                       url(r'^groups/(?P<slug>[\w-]+)/update',
                           views.tavern_group_update,
                           name='tavern_group_update'),
                       url(r'^groups/(?P<slug>[\w-]+)/delete',
                           views.group_delete,
                           name='delete_group'),
                       url(r'^groups/(?P<slug>[\w-]+)/edit_organizer',
                           views.edit_organizers,
                           name='edit_organizers'),
                       url(r'^events/(?P<slug>[\w-]+)/$',
                           views.event_details, name='tavern_event_details'),
                       url(r'^create_event/',
                           views.create_event, name='tavern_create_event'),
                       url(r'^events/(?P<slug>[\w-]+)/update',
                           views.tavern_event_update,
                           name='tavern_event_update'),
                       url(r'^events/(?P<slug>[\w-]+)/delete',
                           views.event_delete,
                           name='delete_event'),
                       url(r'^tavern_toggle_member', views.tavern_toggle_member,
                           name='tavern_toggle_member'),
                       url(r'^rsvp/(?P<event_id>\d+)/(?P<rsvp_status>\w+)/',
                           views.rsvp, name='change_rsvp'),
                       url(r'^rsvp_delete/(?P<pk>\d+)/',
                           views.delete_rsvp, name='delete_rsvp'),
                       )
